### ISSUE TITLE
[Feature request] Extension preferences menu

### ISSUE THREAD

**Issue by FelixFourcolor** [neuromorph/glass_grid#2]
*Hypothetically*, if I disable both the panel indicator and the hotkey shortcut, how can I relaunch the extension?

Should there be a preference menu launchable from extension-manager as a backup way to change the settings, to avoid this situation? Or am I missing something?

Actually it's not hypothetical. I did try to disable them to see what will happen so that I could open this issue, and now I'm stuck. Please advise :joy:

**Comment by neuromorph** [comment]
Lol :smile: , with power comes responsibility! 
The extension doesn't have preferences UI as it is handled through the extension main window. 

In this case, you can use dconf to set the settings for hotkey or indicator. In dconf, path is `/org/gnome/shell/extensions/extgrid/` and the settings are 'hotkey' and 'show-indicator'.

Good catch, anyway. I will add a check to prevent disabling both options in a future update.

Please feel free to provide any other feedback you may have. 

Thank you!

**Comment by FelixFourcolor** [comment]
It works. Thank you.

**Comment by neuromorph** [comment]
Added a check and notification for this scenario as well in the [update from the scaling issue](https://github.com/neuromorph/glass_grid/issues/3#issuecomment-1804113016). You can test this as well.

**Comment by FelixFourcolor** [comment]
I confirm it works.

**Comment by neuromorph** [comment]
Great, thanks for checking!
