### ISSUE TITLE
Panel artifacts when using Blur my Shell

### ISSUE THREAD

**Issue by FelixFourcolor** [neuromorph/glass_grid#5]
https://github.com/neuromorph/glass_grid/assets/34260584/4c0f248f-91b6-488d-912b-eeda25e1e9bb

This can be fixed when you go to Blur my Shell preferences > Panel > enable Static blur

Because it's easily fixed on the user's end, unless it's also easy to fix on your end, I think it suffices to give users a notice on EGO and/or github. Otherwise it's a bit frustrating and took me a while to figure out the cause.

**Comment by neuromorph** [comment]
Ah, the extensions conflict issue, fun /s
OK, I can see why this is happening, both extensions try to do the blur and Gnome has this glitches that need to be overridden through a hack. I will check if I can detect and handle it internally so this does not happen or else I will add the notice as you suggested. 
Good catch. Thanks for reporting.

**Comment by FelixFourcolor** [comment]
Thank you.

**Comment by neuromorph** [comment]
Fix added to same release [as mentioned here](https://github.com/neuromorph/glass_grid/issues/4#issuecomment-1810337076).
